name: Update Azure DevOps Work Item

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  link_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4  
      - name: Extraire le numéro du Work Item depuis le commit
        id: extract_workitem
        run: |
          ID_WORKITEM=$(git log -1 --pretty=format:"%s" | grep -oE '#[0-9]+' | tr -d '#')
          echo "ID_WORKITEM=$ID_WORKITEM" 
          echo "ID_WORKITEM=$ID_WORKITEM" >> $GITHUB_ENV
      - name: Vérification du Work Item
        run: | 
          echo "Work Item ID détecté : $ID_WORKITEM"  


      - name: Mettre à jour le Work Item Azure DevOps
        if: env.ID_WORKITEM != ''
        run: |
          echo "repository: ${{ github.repository }}"
          echo "sha: ${{ github.sha }}"
          curl -X PATCH "https://dev.azure.com/AFPAGuiz/_apis/wit/workitems/$ID_WORKITEM?api-version=6.0" \
            -H "Content-Type: application/json-patch+json" \
            -H "Authorization: Basic $(echo -n :$AZURE_DEVOPS_TOKEN | base64)" \
            -d '[
              {
                "op": "add",
                "path": "/relations/-",
                "value": {
                  "rel": "ArtifactLink",
                  "url": "'"https://github.com/${{ github.repository }}/commit/${{ github.sha }}"'",
                  "attributes": {
                    "name": "GitHub Commit"
                  }
                }
              }
            ]'
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_TOKEN }}
